Add Visual Studio Code instructions
davetcoleman/roscpp_code_format pull request #8
Opened 2018-04-04 12:14 UTC by JeroenDM

Add instructions to README.md to setup clang formatting in Visual Studio Code.

2018-04-04 19:31 UTC, davetcoleman requested changes
love it!

2018-04-04 19:31 UTC, davetcoleman commented on README.md
> +Install the [c/c++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools).
C/C++ should be capitalized

2018-06-22 15:01 UTC, JeroenDM commented
Ping @davetcoleman (I'm not sure whether I'm using "Ping" in the right context :) but the requested change is added.)

2018-06-25 20:44 UTC, merged

2018-06-25 20:44 UTC, davetcoleman commented
Thanks!